/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lisp;


public class App {
    public static void main(String[] args) {
        String input = "()()()";
        System.out.println(LispChecker.validate(input));
    }
}
